"use client";

import { CheckCircle2, History, RotateCcw } from "lucide-react";
import type { DecisionHistory, RecurrenceHistory } from "@/lib/types";
import { dateTimeText, money } from "@/lib/utils";
import { Button } from "@/components/ui";

export function DecisionTimeline({ history, onRefine }: { history: DecisionHistory; onRefine?: (eventId: number) => void }) {
  if (!history.history_found) return <div className="rounded-lg bg-muted p-5"><p className="font-semibold">Экспертные решения отсутствуют</p><p className="mt-2 text-sm text-muted-foreground">Объект ещё не рассматривался специалистом. Первое действие будет сохранено отдельным событием.</p></div>;
  return <ol className="relative border-l-2 border-violet-200 pl-6">{history.events.map((event) => <li key={event.id} className="relative pb-6 last:pb-0"><span className="absolute -left-[31px] top-1 grid h-3 w-3 place-items-center rounded-full bg-primary ring-4 ring-violet-100" aria-hidden="true"/><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{event.action_type}</p><p className="mt-1 text-sm text-muted-foreground">{event.decision_status} · {event.reason_code}</p></div><time className="text-xs text-muted-foreground">{dateTimeText(event.created_at)}</time></div>{event.comment && <p className="mt-3 rounded-md bg-muted p-3 text-sm leading-6">{event.comment}</p>}<div className="mt-2 flex flex-wrap items-center gap-3 text-xs text-muted-foreground"><span>{event.reviewer_display_name}</span><span>Запуск анализа: {event.analysis_run_id ?? "не указан"}</span>{event.supersedes_event_id && <span className="inline-flex items-center gap-1 font-semibold text-violet-700"><RotateCcw className="h-3.5 w-3.5"/>Уточняет событие № {event.supersedes_event_id}</span>}</div>{event.feedback && <details className="mt-3 rounded-md border bg-white p-3"><summary className="cursor-pointer text-sm font-semibold">Обратная связь специалиста</summary><p className="mt-2 text-xs leading-5 text-muted-foreground">Полезность: {event.feedback.usefulness ?? "не оценена"} · качество объяснения: {event.feedback.explanation_quality ?? "не оценено"} · корректность приоритета: {event.feedback.priority_correctness ?? "не оценена"}</p></details>}{onRefine && <Button variant="ghost" className="mt-2" onClick={() => onRefine(event.id)}>Уточнить решение</Button>}</li>)}</ol>;
}

export function RecurrenceHistoryCard({ data, kind }: { data: RecurrenceHistory; kind: "signal" | "pattern" }) {
  const firstLabel = kind === "signal" ? "Этот сигнал обнаружен впервые" : "Эта модель обнаружена впервые";
  if (!data.points.length) return <div className="rounded-lg bg-muted p-5"><p className="font-semibold">{firstLabel}</p><p className="mt-2 text-sm text-muted-foreground">Предыдущая история отсутствует.</p></div>;
  const current = data.points[data.points.length - 1]; const previous = data.points.length > 1 ? data.points[data.points.length - 2] : null;
  const difference = (value: number | null, old: number | null, label: string) => value === null || old === null ? `${label}: недостаточно данных` : value === old ? `${label}: без изменений` : `${label}: ${value - old > 0 ? "+" : ""}${value - old}`;
  const financialChange = previous && current.financial_significance !== null && previous.financial_significance !== null ? Number(current.financial_significance) - Number(previous.financial_significance) : null;
  const currentDoctors = current.participant_signature?.doctors; const previousDoctors = previous?.participant_signature?.doctors; const newDoctors = Array.isArray(currentDoctors) && Array.isArray(previousDoctors) ? currentDoctors.filter((item) => !previousDoctors.includes(item)).length : null;
  return <div><div className="grid gap-3 sm:grid-cols-3"><Metric label="Запусков с появлением" value={String(data.appeared_runs)}/><Metric label="Запусков без появления" value={String(data.absent_runs)}/><Metric label="Последний экспертный вывод" value={data.last_expert_status ?? "Решение отсутствует"}/></div>{previous && <div className="mt-4 rounded-lg bg-blue-50 p-4"><p className="text-sm font-bold">Изменения относительно предыдущего появления</p><ul className="mt-2 grid gap-2 text-sm text-blue-950 sm:grid-cols-2">{kind === "signal" ? <><li>{difference(current.risk_score, previous.risk_score, "Оценка риска")}</li><li>{difference(current.priority_score, previous.priority_score, "Приоритет проверки")}</li></> : <><li>{difference(current.stability_score, previous.stability_score, "Устойчивость")}</li><li>{difference(current.importance_score, previous.importance_score, "Важность")}</li><li>{difference(current.signal_count, previous.signal_count, "Количество сигналов")}</li>{newDoctors !== null && <li>Новых связанных врачей: {newDoctors}</li>}</>}<li>{financialChange === null ? "Финансовая значимость: недостаточно данных" : financialChange === 0 ? "Финансовая значимость: без изменений" : `Финансовая значимость: ${financialChange > 0 ? "+" : ""}${money(financialChange)}`}</li></ul></div>}<div className="mt-4 space-y-2">{data.points.map((point) => <div key={point.analysis_run_id} className="flex flex-wrap items-center justify-between gap-3 rounded-md bg-muted p-3 text-sm"><span className="inline-flex items-center gap-2 font-semibold"><History className="h-4 w-4 text-primary"/>Запуск № {point.analysis_run_id}</span><span className="text-muted-foreground">{point.risk_score !== null ? `Риск ${point.risk_score}` : `Устойчивость ${point.stability_score ?? "—"}`} · {point.priority_score !== null ? `приоритет ${point.priority_score}` : `важность ${point.importance_score ?? "—"}`} · {money(point.financial_significance)}</span><span className="inline-flex items-center gap-1 text-xs text-emerald-700"><CheckCircle2 className="h-4 w-4"/>Объект сформирован</span></div>)}</div></div>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-md bg-violet-50 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-semibold">{value}</p></div>; }
