import Link from "next/link";
import { ArrowRight, ClipboardCheck, TimerReset } from "lucide-react";
import type { ExpertReviewSummary } from "@/lib/types";
import { Card } from "@/components/ui";
import { number } from "@/lib/utils";

export function ExpertWork({ data }: { data: ExpertReviewSummary }) {
  return <Card className="p-6"><div className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><ClipboardCheck className="h-5 w-5 text-primary" aria-hidden="true"/><h2 className="text-lg font-bold">Экспертная работа</h2></div><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Аналитический вывод и решение специалиста хранятся раздельно. Все действия добавляются в последовательную историю.</p></div><div className="flex flex-wrap gap-2"><Link href="/signals?has_decision=false&sort=priority" className="inline-flex min-h-10 items-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-white focus-visible:ring-2 focus-visible:ring-ring">Продолжить проверку<ArrowRight className="h-4 w-4"/></Link><Link href="/decision-journal" className="inline-flex min-h-10 items-center rounded-md border bg-white px-4 text-sm font-semibold focus-visible:ring-2 focus-visible:ring-ring">Открыть журнал решений</Link></div></div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-5"><Metric label="Сигналов без решения" value={number(data.signals_without_decision)}/><Metric label="Моделей без решения" value={number(data.patterns_without_decision)}/><Metric label="Начатых проверок" value={number(data.in_progress)}/><Metric label="Завершено" value={number(data.completed_current_period)}/><Metric label="Средний срок" value={data.average_first_decision_hours === null ? "Недостаточно данных" : `${data.average_first_decision_hours.toFixed(1).replace(".", ",")} ч`} icon/></div>{!data.sample_sufficient && <p className="mt-4 rounded-md bg-amber-50 p-3 text-sm text-amber-950">{data.sample_message}</p>}</Card>;
}

function Metric({ label, value, icon = false }: { label: string; value: string; icon?: boolean }) { return <div className="rounded-lg bg-muted p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 flex items-center gap-2 font-bold">{icon && <TimerReset className="h-4 w-4 text-primary"/>}{value}</p></div>; }
