"use client";

import { useEffect, useId, useState } from "react";
import { CheckCircle2, FileQuestion, MessageSquareText, SearchCheck, Send } from "lucide-react";
import type { PatternReviewStatus } from "@/lib/types";
import { Button, Card, Select } from "./ui";

type PatternChoice = { status: PatternReviewStatus; commentOnly?: boolean };

export function PatternReviewActions({ currentStatus, onChoose }: { currentStatus: PatternReviewStatus; onChoose: (choice: PatternChoice) => void }) {
  return <div className="flex items-center justify-end gap-2" aria-label="Экспертная оценка модели">
    <Button onClick={() => onChoose({ status: "Направлено на углублённую проверку" })} className="min-w-0 flex-1 sm:flex-none"><Send className="h-4 w-4" aria-hidden="true" />Направить на углублённую проверку</Button>
    <details className="group relative"><summary className="inline-flex min-h-10 cursor-pointer list-none items-center justify-center rounded-md bg-secondary px-4 text-sm font-semibold text-secondary-foreground hover:bg-secondary/70 focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2">Другие действия</summary><div className="absolute bottom-full right-0 z-50 mb-2 hidden w-[min(21rem,calc(100vw-2rem))] rounded-lg bg-card p-3 shadow-xl group-open:block"><p className="px-2 pb-2 text-xs font-bold uppercase tracking-wider text-muted-foreground">Решение</p><div className="space-y-1"><Button className="w-full justify-start" variant="ghost" onClick={() => onChoose({ status: "Значимость подтверждена" })}><CheckCircle2 className="h-4 w-4" aria-hidden="true" />Подтвердить значимость</Button><Button className="w-full justify-start" variant="ghost" onClick={() => onChoose({ status: "Отмечено как несущественное" })}><SearchCheck className="h-4 w-4" aria-hidden="true" />Признать несущественной</Button></div><div className="mt-2 space-y-1 border-t pt-2"><Button className="w-full justify-start" variant="ghost" onClick={() => onChoose({ status: "Требуются дополнительные сведения" })}><FileQuestion className="h-4 w-4" aria-hidden="true" />Запросить сведения</Button><Button className="w-full justify-start" variant="ghost" onClick={() => onChoose({ status: currentStatus, commentOnly: true })}><MessageSquareText className="h-4 w-4" aria-hidden="true" />Добавить комментарий</Button></div></div></details>
  </div>;
}

export function PatternReviewDialog({ choice, saving, onCancel, onSave }: { choice: PatternChoice; saving: boolean; onCancel: () => void; onSave: (comment: string, reasonCode: string) => void }) {
  const [comment, setComment] = useState("");
  const reasons = choice.status === "Отмечено как несущественное" ? ["допустимое организационное отклонение", "неполные исходные данные", "недостаточная сопоставимая группа", "иная причина"] : choice.status === "Направлено на углублённую проверку" || choice.status === "Требуются дополнительные сведения" ? ["требуется запрос документов", "требуется проверка организации", "требуется проверка связанных сигналов", "требуется дополнительная выборка данных", "иная причина"] : ["данные подтверждают отклонение", "повторяемость требует дополнительного внимания", "существенная финансовая значимость", "подтверждено сопоставлением с документами", "подтверждено медицинским экспертом", "иная причина"];
  const [reason, setReason] = useState(reasons[0]);
  const titleId = useId();
  const commentId = useId();
  const required = choice.status === "Отмечено как несущественное" || reason === "иная причина";
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === "Escape") onCancel(); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, [onCancel]);
  const explanation = choice.commentOnly ? "Комментарий будет добавлен в историю без изменения статуса модели." : choice.status === "Значимость подтверждена" ? "Модель останется в рабочем списке как значимая для экспертной проверки." : choice.status === "Отмечено как несущественное" ? "Модель будет отмечена как несущественная для текущего контекста. Добавьте основание решения." : "Модель будет направлена на углублённую экспертную проверку вместе со связанными сигналами.";
  return <div className="fixed inset-0 z-[80] grid place-items-center p-4"><button type="button" className="absolute inset-0 bg-slate-950/55 backdrop-blur-sm" onClick={onCancel} aria-label="Закрыть окно оценки" /><Card role="dialog" aria-modal="true" aria-labelledby={titleId} className="relative w-full max-w-lg p-6 shadow-xl"><h2 id={titleId} className="text-xl font-bold">{choice.commentOnly ? "Добавить комментарий" : "Подтвердить экспертную оценку"}</h2>{!choice.commentOnly && <p className="mt-2 text-sm">Новый статус: <strong>{choice.status}</strong></p>}<p className="mt-2 text-sm leading-6 text-muted-foreground">{explanation}</p><label className="mt-5 block text-sm font-semibold">Причина решения<Select className="mt-2 w-full" value={reason} onChange={(event) => setReason(event.target.value)}>{reasons.map((item) => <option key={item}>{item}</option>)}</Select></label><label htmlFor={commentId} className="mt-5 block text-sm font-semibold">Комментарий специалиста{required ? " — обязательно" : ""}</label><textarea id={commentId} value={comment} onChange={(event) => setComment(event.target.value)} rows={4} maxLength={2000} aria-required={required} className="mt-2 w-full rounded-md border bg-card p-3 text-sm focus-visible:ring-2 focus-visible:ring-ring" placeholder="Укажите медицинский или организационный контекст" />{required && !comment.trim() && <p className="mt-2 text-xs text-muted-foreground">Для этого решения требуется краткое обоснование.</p>}<div className="mt-5 flex justify-end gap-2"><Button variant="ghost" disabled={saving} onClick={onCancel}>Отмена</Button><Button disabled={saving || (required && !comment.trim())} aria-busy={saving} onClick={() => onSave(comment.trim(), reason)}>{saving ? "Сохранение…" : choice.commentOnly ? "Добавить комментарий" : "Сохранить оценку"}</Button></div></Card></div>;
}

export type { PatternChoice };
