import type { CommandCenter, PatternDetail, PatternGraph, PatternSummary, RecurringPattern, SignalDetail } from "@/lib/types";

export const commandCenterFixture: CommandCenter = {
  new_high_critical_signals: 47,
  high_risk_organizations: 3,
  review_amount: "12400000",
  signals_without_decision: 91,
  last_analysis_at: "2026-07-12T09:30:00",
  comparison_available: true,
  priority_organization: {
    id: 4,
    name: "Центр диагностики № 4",
    high_risk_signals: 38,
    review_amount: "12400000",
    risk_score: 88,
    priority_score: 91,
    priority_level: "Критический",
    main_reason: "Финансовая значимость",
    summary: "Наибольшего внимания требует медицинская организация «Центр диагностики № 4»: 38 сигналов высокого и критического риска на сумму 12,4 млн тенге.",
  },
  high_critical_amount: "12400000",
  potential_review_amount: "15100000",
  priority_patients: 72,
  top_financial_signal: {id: 10, organization_name: "Центр диагностики № 4", service_name: "Компьютерная томография", priority_score: 92, priority_level: "Критический", financial_significance: "780000"},
};

export const signalFixture: SignalDetail = {
  id: 10,
  date: "2026-06-28",
  organization_id: 4,
  organization_name: "Центр диагностики № 4",
  organization_type: "диагностический центр",
  patient_code: "PT-000010",
  service_name: "Компьютерная томография",
  amount: "54000",
  score: 88,
  level: "Критический",
  primary_reason: "Отклонение стоимости",
  anomaly_type: "Отклонение стоимости",
  status: "Не проверено",
  region: "Астана",
  priority_score: 92,
  priority_level: "Критический",
  financial_significance: "780000",
  priority_factors: [{name: "Оценка риска", weight: 40, normalized_value: 88, contribution: 35, actual_value: "88 из 100", typical_value: "шкала риска", explanation: "Высокая оценка риска повышает приоритет."}],
  priority_explanation: "Критический приоритет сформирован из-за риска и финансовой значимости.",
  rule_score: 82,
  organization_score: 71,
  financial_score: 90,
  factors: [{name: "Отклонение стоимости", contribution: 45, actual_value: "54 000 тенге", typical_value: "31 000 тенге", explanation: "Стоимость выше медианы сопоставимой группы на 74%."}],
  related_services: [{record_id: 22, date: "2026-06-27", time: "10:20", name: "Консультация специалиста", amount: "8000", organization_name: "Центр диагностики № 4", related_signal_id: null, relationship_explanation: "Услуга оказана тому же пациенту в близкий период."}],
  reviews: [],
  limitations: ["Анализ основан на доступных обезличенных данных."],
  recommendation: "Рекомендуется приоритетная экспертная проверка.",
  repetition_count: 3,
  affected_patients: 1,
  duration_days: 2,
};

export const patternFixture: RecurringPattern = {
  id: 7,
  fingerprint: "f".repeat(64),
  name: "Повторяющаяся услуга: Холтеровское мониторирование",
  pattern_type: "repeated_service",
  pattern_type_label: "Повторяющаяся услуга",
  description: "В течение четырёх периодов сформировано 38 связанных сигналов.",
  first_seen: "2026-02-03",
  last_seen: "2026-06-28",
  period_count: 4,
  signal_count: 38,
  organization_count: 1,
  doctor_count: 2,
  patient_count: 21,
  service_count: 1,
  financial_significance: "4800000",
  average_risk: 82,
  average_priority: 88,
  stability_score: 84,
  stability_level: "Очень высокая",
  importance_score: 91,
  importance_level: "Критический",
  review_status: "Не оценено",
  formed_at: "2026-07-13T09:00:00",
  main_organization: "Центр диагностики Оңтүстік",
  primary_reason: "Услуга повторяется в четырёх периодах.",
};

export const patternDetailFixture: PatternDetail = {
  ...patternFixture,
  recurrence_runs: 3,
  explanation: "В течение четырёх периодов сформировано 38 связанных сигналов.",
  disclaimer: "Повторяющаяся модель отражает устойчивое сочетание сигналов и связей в доступных данных. Это аналитический контекст, который требует экспертной оценки.",
  limitations: ["Анализ основан на доступных обезличенных данных.", "Итоговое решение принимает уполномоченный специалист."],
  factors: [
    { factor_group: "Устойчивость", name: "Количество периодов", weight: 25, normalized_value: 100, contribution: 25, actual_value: "4 периода", typical_value: "четыре периода", explanation: "Фактор показывает регулярность." },
    { factor_group: "Важность", name: "Средняя оценка риска", weight: 25, normalized_value: 82, contribution: 21, actual_value: "82 из 100", typical_value: "шкала риска", explanation: "Фактор определяет важность." },
  ],
  organizations: [{ id: 4, label: "Центр диагностики Оңтүстік", signal_count: 38, financial_significance: "4800000", share: null, is_primary: true }],
  doctors: [{ id: 12, label: "DR-000012", signal_count: 27, financial_significance: null, share: 0.71, is_primary: true }],
  patients: [{ id: 22, label: "PT-000022", signal_count: 3, financial_significance: null, share: 0.08, is_primary: false }],
  services: [{ id: 17, label: "Холтеровское мониторирование", signal_count: 38, financial_significance: "4800000", share: null, is_primary: true }],
  reviews: [],
};

export const patternSummaryFixture: PatternSummary = {
  analysis_run_id: 8,
  total_patterns: 42,
  high_stability_patterns: 18,
  financial_significance: "21600000",
  affected_organizations: 14,
  stable_pattern_organizations: 11,
  affected_patients: 306,
  new_patterns: 4,
  top_importance_pattern: patternFixture,
  top_financial_pattern: patternFixture,
  attention_patterns: [patternFixture],
  disclaimer: patternDetailFixture.disclaimer,
};

export const patternGraphFixture: PatternGraph = {
  pattern_id: 7,
  nodes: [
    { id: "pattern-7", node_type: "pattern", label: patternFixture.name, subtitle: "Важность 91 из 100", size: 34, signal_count: 38, financial_significance: "4800000", href: "/patterns/7", is_primary: true },
    { id: "organization-4", node_type: "organization", label: "Центр диагностики Оңтүстік", subtitle: "38 сигналов", size: 28, signal_count: 38, financial_significance: "4800000", href: "/organizations/4", is_primary: true },
    { id: "doctor-12", node_type: "doctor", label: "DR-000012", subtitle: "27 сигналов", size: 22, signal_count: 27, financial_significance: "0", href: null, is_primary: true },
    { id: "service-17", node_type: "service", label: "Холтеровское мониторирование", subtitle: "38 сигналов", size: 25, signal_count: 38, financial_significance: "4800000", href: null, is_primary: true },
    { id: "patient-22", node_type: "patient", label: "PT-000022", subtitle: "3 сигнала", size: 16, signal_count: 3, financial_significance: "0", href: null, is_primary: false },
    { id: "signal-10", node_type: "signal", label: "Сигнал № 10", subtitle: "Холтеровское мониторирование", size: 18, signal_count: 1, financial_significance: "780000", href: "/signals/10", is_primary: false },
  ],
  edges: [
    { id: "p-s", source: "pattern-7", target: "signal-10", relationship: "модель включает сигнал", weight: 1 },
    { id: "s-o", source: "signal-10", target: "organization-4", relationship: "сигнал относится к организации", weight: 1 },
  ],
  hidden_nodes: 0,
  legend: { pattern: "Повторяющаяся модель", organization: "Медицинская организация" },
};
