"use client";

import Link from "next/link";
import { useParams } from "next/navigation";
import { ArrowLeft, ArrowRight, Building2, CircleDollarSign, FileSearch, Gauge, MapPin, Network, Stethoscope } from "lucide-react";
import { api } from "@/lib/api";
import { useApi } from "@/hooks/use-api";
import { money, number, percent } from "@/lib/utils";
import { Card } from "@/components/ui";
import { ErrorState, PageLoading, EmptyState } from "@/components/data-state";
import { RiskBadge } from "@/components/risk-badge";
import { PriorityBadge } from "@/components/priority-badge";
import { StatusBadge } from "@/components/status-badge";
import { TimelineChart, RiskDonut } from "@/components/charts";
import { OrganizationComparisonBlock } from "@/components/organization-comparison";
import { PrioritySparkline } from "@/components/priority-sparkline";
import { FinancialDisclaimer } from "@/components/financial-disclaimer";
import { PatternTypeBadge, StabilityBadge } from "@/components/pattern-badges";

export default function OrganizationPage() {
  const params = useParams<{id: string}>();
  const state = useApi(() => api.organization(params.id), [params.id]);
  const comparison = useApi(() => api.organizationComparison(params.id), [params.id]);
  const patterns = useApi(() => api.organizationPatterns(params.id), [params.id]);
  if (state.loading || comparison.loading || patterns.loading) return <div className="page-shell"><PageLoading/></div>;
  const error = state.error || comparison.error;
  if (error || !state.data || !comparison.data) return <div className="page-shell"><ErrorState message={error ?? "Нет данных"} retry={() => {void state.retry(); void comparison.retry();}}/></div>;
  const org = state.data;
  return <div className="page-shell">
    <Link href="/organizations" className="mb-5 inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-muted-foreground hover:text-primary focus-visible:ring-2 focus-visible:ring-ring"><ArrowLeft className="h-4 w-4" aria-hidden="true"/>К списку организаций</Link>
    <header className="flex flex-col gap-5 lg:flex-row lg:items-start lg:justify-between"><div><div className="mb-3 flex flex-wrap gap-2">{org.priority_level && <PriorityBadge level={org.priority_level}/>}<StatusBadge status={org.review_status}/></div><h1 className="max-w-4xl text-3xl font-bold tracking-tight md:text-4xl">{org.name}</h1><p className="mt-3 flex flex-wrap gap-x-5 gap-y-2 text-sm text-muted-foreground"><span className="flex items-center gap-1.5"><MapPin className="h-4 w-4" aria-hidden="true"/>{org.region}</span><span className="flex items-center gap-1.5"><Building2 className="h-4 w-4" aria-hidden="true"/>{org.organization_type}</span></p></div><Link href={`/signals?organization_id=${org.id}&sort=priority`} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-white shadow-glow focus-visible:ring-2 focus-visible:ring-ring">Открыть сигналы организации<FileSearch className="h-4 w-4" aria-hidden="true"/></Link></header>
    <section className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={FileSearch} label="Приоритет проверки" value={org.priority_score == null ? "Не рассчитан" : `${org.priority_score} из 100`} detail={`Оценка риска: ${org.risk_score} из 100 · ${org.risk_level}`} emphasis/><Metric icon={CircleDollarSign} label="Финансовая значимость" value={money(org.financial_significance)} detail={`Общая сумма услуг: ${money(org.total_amount)}`}/><Metric icon={Stethoscope} label="Количество сигналов" value={number(org.signals_count)} detail={`${number(org.affected_patients)} пациентов · ${percent(org.unreviewed_share)} без решения`}/><Metric icon={Gauge} label="Главное отклонение" value={org.primary_reason} detail="Основная причина текущего приоритета"/></section>
    <section className="mt-5 grid gap-4 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-6"><h2 className="text-lg font-bold">Почему организация имеет такой приоритет</h2>{org.priority_factors.length ? <div className="mt-4 space-y-3">{org.priority_factors.slice(0,5).map(factor => <div key={factor.name} className="rounded-lg bg-violet-50 p-4"><div className="flex flex-wrap justify-between gap-3"><p className="font-semibold">{factor.name}</p><strong className="font-mono tabular-nums text-violet-800">+{factor.contribution}</strong></div><p className="mt-2 text-sm text-muted-foreground">{factor.actual_value} · сравнение: {factor.typical_value}</p><p className="mt-2 text-sm leading-6 text-muted-foreground">{factor.explanation}</p></div>)}</div> : <p className="mt-3 text-sm text-muted-foreground">Приоритет появится после завершения анализа.</p>}</Card><Card className="p-6"><h2 className="text-lg font-bold">Динамика приоритета</h2><div className="mt-5"><PrioritySparkline history={org.priority_history}/></div><div className="mt-5 space-y-2 text-sm text-muted-foreground"><p>Изменение приоритета: {org.priority_change == null ? "недостаточно запусков" : `${org.priority_change > 0 ? "+" : ""}${org.priority_change} пунктов`}</p><p>Изменение финансовой значимости: {org.financial_change == null ? "недостаточно запусков" : money(org.financial_change)}</p></div></Card></section>
    <div className="mt-5"><FinancialDisclaimer/></div>
    <section className="mt-5"><OrganizationComparisonBlock data={comparison.data}/></section>
    <section className="mt-5"><Card className="p-6"><div className="flex items-center gap-2"><Network className="h-5 w-5 text-primary" aria-hidden="true"/><h2 className="text-lg font-bold">Повторяющиеся модели организации</h2></div>{patterns.error ? <div className="mt-4 rounded-lg bg-amber-50 p-4"><p className="text-sm font-semibold">Не удалось загрузить модели организации</p><button type="button" className="mt-2 min-h-10 text-sm font-semibold text-primary focus-visible:ring-2 focus-visible:ring-ring" onClick={() => void patterns.retry()}>Повторить</button></div> : patterns.data?.length ? <div className="mt-5 grid gap-3 md:grid-cols-2">{patterns.data.slice(0,6).map(pattern => <Link key={pattern.id} href={`/patterns/${pattern.id}`} className="group rounded-lg bg-gradient-to-br from-slate-50 to-violet-50 p-4 focus-visible:ring-2 focus-visible:ring-ring"><div className="flex flex-wrap gap-2"><PatternTypeBadge label={pattern.pattern_type_label}/><StabilityBadge level={pattern.stability_level} score={pattern.stability_score}/></div><p className="mt-3 font-semibold group-hover:text-primary">{pattern.name}</p><p className="mt-2 text-sm text-muted-foreground">{pattern.signal_count} сигналов · {pattern.period_count} периодов · {money(pattern.financial_significance)}</p><span className="mt-3 inline-flex min-h-10 items-center gap-1 text-sm font-semibold text-primary">Открыть модель<ArrowRight className="h-4 w-4" aria-hidden="true"/></span></Link>)}</div> : <p className="mt-3 text-sm text-muted-foreground">Повторяющиеся модели пока не сформированы. Для анализа требуется несколько периодов наблюдений.</p>}</Card></section>
    <details className="group mt-5 rounded-lg bg-card shadow-card"><summary className="flex min-h-14 cursor-pointer list-none items-center justify-between gap-3 px-6 py-4 font-semibold focus-visible:ring-2 focus-visible:ring-ring">Дополнительная аналитика<span className="text-sm font-normal text-muted-foreground group-open:hidden">Показать динамику и распределение риска</span></summary><div className="grid gap-4 border-t p-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="p-6"><Title text="Динамика медицинских услуг"/><TimelineChart data={org.timeline}/></Card><Card className="p-6"><Title text="Распределение по уровням риска"/><RiskDonut data={org.risk_distribution}/></Card></div></details>
    <section className="mt-5"><Card className="overflow-hidden"><div className="p-6"><Title text="Последние сигналы"/></div>{org.recent_signals.length ? <div className="divide-y">{org.recent_signals.map(signal => <Link href={`/signals/${signal.id}`} key={signal.id} className="flex min-h-16 items-center gap-4 px-6 py-3 hover:bg-muted focus-visible:ring-2 focus-visible:ring-ring"><span className="font-mono text-lg font-bold tabular-nums">{signal.priority_score ?? signal.score}</span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{signal.service_name}</span><span className="text-xs text-muted-foreground">{signal.primary_reason} · {money(signal.financial_significance)}</span></span>{signal.priority_level ? <PriorityBadge level={signal.priority_level}/> : <RiskBadge level={signal.level}/>}</Link>)}</div> : <EmptyState description="Сигналы по организации не сформированы."/>}</Card></section>
  </div>;
}

function Metric({icon: Icon, label, value, detail, emphasis = false}: {icon: typeof Building2; label: string; value: string; detail?: string; emphasis?: boolean}) { return <Card className={`min-w-0 p-5 ${emphasis ? "border-priority/15 bg-gradient-to-br from-priority-soft via-card to-card" : ""}`}><span className={`grid h-10 w-10 place-items-center rounded-md ${label === "Финансовая значимость" ? "bg-finance-soft text-finance" : emphasis ? "bg-priority-soft text-priority" : "bg-surface-soft text-primary"}`}><Icon className="h-5 w-5" aria-hidden="true"/></span><p className={`mt-4 text-sm font-semibold ${emphasis ? "text-priority" : "text-muted-foreground"}`}>{label}</p><p className={`mt-1 break-words font-mono font-bold tracking-tight tabular-nums ${emphasis ? "text-3xl text-priority" : "text-xl"}`}>{value}</p>{detail && <p className="mt-2 text-xs leading-5 text-muted-foreground">{detail}</p>}</Card>; }
function Title({text}: {text: string}) { return <h2 className="text-lg font-bold">{text}</h2>; }
